// Generated by CoffeeScript 1.6.3
$(function() {
  var $player, $team;
  $team = $('.js-team-autocomplete .typeahead');
  $team.typeahead({
    name: 'team1',
    prefetch: 'data/footballTeamList.json',
    template: ['<p class=""><img src="{{image}}" />{{value}}</p>'].join(''),
    engine: Hogan
  });
  $team.on("typeahead:selected", function(event, data) {
    if (data.url) {
      return window.location = data.url;
    }
  });
  $player = $('.js-player-autocomplete .typeahead');
  $player.typeahead({
    name: 'player',
    prefetch: 'data/footballPlayerList.json',
    template: ['<p class=""><img src="{{image}}" />{{value}}</p>'].join(''),
    engine: Hogan
  });
  return $player.on("typeahead:selected", function(event, data) {
    if (data.url) {
      return window.location = data.url;
    }
  });
});
