// Generated by CoffeeScript 1.6.3
$(function() {
  var $team;
  $team = $('.js-football-team-autocomplete .typeahead');
  $team.typeahead({
    name: 'team2',
    prefetch: 'data/footballTeamList.json',
    template: ['<p class=""><img src="{{image}}" /> {{value}}</p>'].join(''),
    engine: Hogan
  });
  return $team.on("typeahead:selected", function(event, selectedDatum, datasetName) {
    if (selectedDatum.url) {
      return window.location = selectedDatum.url;
    }
  });
});

$(function() {
  var $player;
  $player = $('.js-football-player-autocomplete .typeahead');
  $player.typeahead({
    name: 'player',
    prefetch: 'data/footballPlayerList.json',
    template: ['<p class=""><img src="{{image}}" /> {{value}}</p>'].join(''),
    engine: Hogan
  });
  return $player.on("typeahead:selected", function(event, selectedDatum, datasetName) {
    if (selectedDatum.url) {
      return window.location = selectedDatum.url;
    }
  });
});

$(function() {
  var $all;
  $all = $('.js-football-all-autocomplete .typeahead');
  $all.typeahead([
    {
      name: 'team2',
      prefetch: 'data/footballTeamList.json',
      header: '<h3 class="">Equipes de football</h3>',
      template: ['<p class=""><img src="{{image}}" /> {{value}}</p>'].join(''),
      engine: Hogan,
      limit: 3
    }, {
      name: 'player',
      prefetch: 'data/footballPlayerList.json',
      header: '<h3 class="">Joueurs de football</h3>',
      template: ['<p class=""><img src="{{image}}" /> {{value}}</p>'].join(''),
      engine: Hogan,
      limit: 3
    }
  ]);
  return $all.on("typeahead:selected", function(event, selectedDatum, datasetName) {
    if (selectedDatum.url) {
      return window.location = selectedDatum.url;
    }
  });
});
